### ISSUE TITLE
[HELP] Is Assign an atomic operation?

### ISSUE THREAD

**Issue by shubhamkumar13** [IUCompilerCourse/python-student-support-code#34]
for the following statements
```py
a = 42
print(a)
```
The expected `L_mon_var` syntax shouldn't change because we don't want to add unnecessary temp variables
so it should look same.

This means the case statements for pattern matching `print` 
https://github.com/IUCompilerCourse/python-student-support-code/blob/334ca05c40ff91028b4e26cc8ffb3a57a42fffe4/compiler.py#L61
in `rco_stmt` requires a pattern match on `Assign(...)` in `rco_exp` which is absent

or 

A recursive call to `rco_stmt` where we already have a `Assign(...)`
https://github.com/IUCompilerCourse/python-student-support-code/blob/334ca05c40ff91028b4e26cc8ffb3a57a42fffe4/compiler.py#L67
but that would imply that the `print` statement doesn't print an expression but a statement

I think I'm missing something here, can anyone help me?

My AST might be wrong, so I am pasting it here for reference
```py
    forty_two = Constant(42)
    a = Name("a")
    s1 = Assign([a], forty_two)
    s2 = Call(Name("print"), [s1])
    pr = Expr(s2)
    p = Module([pr])
    c = Compiler()
    d = c.remove_complex_operands(p)
    # e = c.select_instructions(d)
    # f = c.assign_homes(e)
    print(d)
 ```

**Comment by shubhamkumar13** [comment]
I tried adding multiple statements in the `Module(...)` dataclass and also made them individual and not chained as I did above and it kind of gives me what I expect 

Modified Snippet
```py
    forty_two = Constant(42)
    a = Name("a")
    b = Name("b")
    s1 = Assign([a], forty_two)
    s2 = Assign([b], a)
    s3 = Expr(Call(Name("print"), [a]))
    p = Module([s1, s2, s3])
    c = Compiler()
    d = c.remove_complex_operands(p)
    print(d)
    e = c.select_instructions(d)
    print(e)
    f = c.assign_homes(e)
    print(f)
 ```
 Output :
 ```bash
    a = 42
    b = a
    print(a)

        .globl main
main:
    movq $42, a
    movq a, b
    movq a, %rdi
    callq print_int


        .globl main
main:
    movq $42, -8(%rbp)
    movq -8(%rbp), -16(%rbp)
    movq -8(%rbp), %rdi
    callq print_int 
```
 
so my AST representation might be wrong, but still would be happy if someone can confirm it

**Comment by DarshalShetty** [comment]
Why would you want to handle `Assign` statements when your RCO pass is handling the call to `print`? By the time the `rco_stmt` function removes complex operands from the `print` in your first example python code, it has already handled removing complex operands from the `Assign` statement in the previous line. Thus, the `print` case in `rco_stmt` should focus on handling the call to `print` with a `Var` argument in your example code. The `print` case or any other case should not bother with statements before it because the current compiler pass has already been applied on them as you can see in the `remove_complex_operands` function. 

If you are worried about malformed AST then you should use the `parse` function from Python's `ast` module. It accepts a string containing a Python program and returns a well-formed Python AST which we can use in the compiler. 

The output of your second Python example seems correct to me. Is there something specific that is bothering you?

**Comment by DarshalShetty** [comment]
To answer your question in the title of this post directly: no. Only expressions can be atomic. `Assign` is a statement and not an expression.

**Comment by shubhamkumar13** [comment]
I think I made a mistake, I didn't realize `print (a = 42)` would never be a valid statement because we just print `42` so I might be wrong. Thanks for the help!
